# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_cookie_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='version',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
