
-- CREATE USER 'pbreader' IDENTIFIED BY '[PUT ACTUAL PASSWORD HERE]';
GRANT SELECT ON `pb`.* TO 'pbreader';
-- CREATE USER 'pbadder' IDENTIFIED BY '[PUT ACTUAL PASSWORD HERE]';
GRANT INSERT ON `pb`.* TO 'pbadder';
