# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('label', models.CharField(max_length=200)),
                ('version', models.SmallIntegerField(choices=[(4, '4'), (6, '6')])),
                ('asn', models.IntegerField(blank=True, null=True)),
                ('isp', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(max_length=63)),
                ('region', models.CharField(max_length=127)),
                ('town', models.CharField(max_length=127)),
                ('zip', models.CharField(max_length=31)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(max_length=8)),
                ('scheme', models.CharField(max_length=8)),
                ('host', models.CharField(max_length=1023)),
                ('path', models.CharField(max_length=4095)),
                ('query_str', models.CharField(max_length=4095)),
                ('referrer', models.URLField(blank=True, max_length=4095, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('cookie1', models.CharField(blank=True, max_length=24, null=True)),
                ('cookie2', models.CharField(blank=True, max_length=24, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('label', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traffic.User')),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traffic.Visitor'),
        ),
    ]
