# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(max_length=8)),
                ('host', models.CharField(max_length=1023)),
                ('url', models.TextField()),
                ('referrer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=39)),
                ('cookie1', models.CharField(blank=True, max_length=16, null=True)),
                ('cookie2', models.CharField(blank=True, max_length=24, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('is_me', models.NullBooleanField(default=None)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traffic.Visitor'),
        ),
    ]
