# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('page', models.TextField()),
                ('referrer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie1', models.CharField(max_length=16)),
                ('cookie2', models.CharField(max_length=24)),
                ('ip', models.CharField(max_length=39)),
                ('user_agent', models.CharField(max_length=200)),
                ('is_me', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traffic.Visitor'),
        ),
    ]
