# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-04 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_robots'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='referrer',
            field=models.URLField(blank=True, db_index=True, max_length=4095, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='user_agent',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
