# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-07 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_robot_referrer_and_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipinfo',
            name='hostname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipinfo',
            name='timezone',
            field=models.CharField(default='', max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ipinfo',
            name='version',
            field=models.SmallIntegerField(blank=True, choices=[(4, '4'), (6, '6')], null=True),
        ),
        migrations.AlterField(
            model_name='ipinfo',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
