# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0006_ipinfo_enhance'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='location',
            field=models.URLField(blank=True, max_length=4095, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='response',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
