# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-23 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.misc


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0007_response_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_version', models.PositiveSmallIntegerField(null=True)),
                ('captcha_failed', models.NullBooleanField()),
                ('honeypot_name', models.CharField(max_length=31)),
                ('honeypot_value', models.TextField(null=True)),
                ('honeypot_overflow', models.BooleanField()),
                ('checkboxes_str', models.CharField(max_length=18)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_overflow', models.BooleanField()),
                ('js_enabled', models.NullBooleanField()),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic.Visit')),
            ],
            bases=(utils.misc.ModelMixin, models.Model),
        ),
    ]
