# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-23 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0008_log_spam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spam',
            name='content_overflow',
        ),
        migrations.RemoveField(
            model_name='spam',
            name='honeypot_overflow',
        ),
        migrations.AddField(
            model_name='spam',
            name='content_len',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spam',
            name='honeypot_len',
            field=models.IntegerField(null=True),
        ),
    ]
