# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.misc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traffic', '0006_ipinfo_enhance'),
        ('notepad', '0006_move_visit_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('attributes', models.TextField()),
            ],
            bases=(utils.misc.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('list', 'list'), ('position', 'position')], max_length=127)),
                ('old_display_order', models.IntegerField(null=True)),
                ('new_display_order', models.IntegerField(null=True)),
            ],
            bases=(utils.misc.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='editpages.Item')),
                ('display_order', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('adding_visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_listitem', to='traffic.Visit')),
                ('deleting_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_listitem', to='traffic.Visit')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='editpages.ListItem')),
            ],
            bases=('editpages.item',),
        ),
        migrations.AddField(
            model_name='move',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='editpages.Item'),
        ),
        migrations.AddField(
            model_name='move',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editpages_move', to='traffic.Visit'),
        ),
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editpages_item', to='notepad.Note'),
        ),
        migrations.AddField(
            model_name='move',
            name='new_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves_to', to='editpages.ListItem'),
        ),
        migrations.AddField(
            model_name='move',
            name='old_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves_from', to='editpages.ListItem'),
        ),
    ]
