# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editpages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='attributes',
        ),
    ]
