# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0006_move_visit_fix'),
        ('editpages', '0002_rm_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='attributes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attr_item', to='notepad.Note'),
        ),
    ]
