# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminDigest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=63)),
                ('hash', models.CharField(max_length=63)),
                ('iterations', models.IntegerField()),
                ('salt', models.CharField(max_length=128)),
                ('digest', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AdminPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='admindigest',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.AdminPassword'),
        ),
    ]
