# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='deleting_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_note', to='traffic.Visit'),
        ),
    ]
