# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-08 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0002_one_visit_many_deletions'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='display_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='last_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_version', to='notepad.Note'),
        ),
    ]
