# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 10:20
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F


def init_display_order(apps, schema_editor):
    """Set the initial display order to the Note.id."""
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version.
    db_alias = schema_editor.connection.alias
    Note = apps.get_model("notepad", "Note")
    notes = Note.objects.using(db_alias).all()
    notes.update(display_order=F('id'))


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0003_display_and_last_version'),
    ]

    operations = [
        # init_display_order() just sets values on the display_order field created by the migration.
        # In reverse, the field just needs to be deleted. This is already take care of by the migration.
        migrations.RunPython(init_display_order, migrations.RunPython.noop),
    ]
