# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.misc


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0006_ipinfo_enhance'),
        ('notepad', '0004_set_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('page', 'page'), ('position', 'position')], max_length=127)),
                ('old_display_order', models.IntegerField(null=True)),
                ('new_display_order', models.IntegerField(null=True)),
                ('new_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves_to', to='notepad.Page')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notepad.Note')),
                ('old_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves_from', to='notepad.Page')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='traffic.Visit')),
            ],
            bases=(utils.misc.ModelMixin, models.Model),
        ),
    ]
