# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0005_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traffic.Visit'),
        ),
    ]
