# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-16 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0007_response_code'),
        ('notepad', '0007_nonunique_note_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='archiving_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_note', to='traffic.Visit'),
        ),
    ]
